// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUR4hgWcu_dly7ahpWUmIsJWG-xEiv8E',
    appId: '1:455094239164:web:1a2354a631d685d63ff5b9',
    messagingSenderId: '455094239164',
    projectId: 'lebanon-driving-practice',
    authDomain: 'lebanon-driving-practice.firebaseapp.com',
    storageBucket: 'lebanon-driving-practice.firebasestorage.app',
    measurementId: 'G-1CF0HZG2HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDc083Eqf2R3YJrApNJcXCmBijs7rV9dY',
    appId: '1:455094239164:android:fca706eb200247b43ff5b9',
    messagingSenderId: '455094239164',
    projectId: 'lebanon-driving-practice',
    storageBucket: 'lebanon-driving-practice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6dXfR6d1oPViQFv2nSiV8KVHmhiPgbpU',
    appId: '1:455094239164:ios:29770f00d50bce703ff5b9',
    messagingSenderId: '455094239164',
    projectId: 'lebanon-driving-practice',
    storageBucket: 'lebanon-driving-practice.firebasestorage.app',
    iosBundleId: 'com.royapps.lebanondrivingexam.lebanonDrivingExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6dXfR6d1oPViQFv2nSiV8KVHmhiPgbpU',
    appId: '1:455094239164:ios:29770f00d50bce703ff5b9',
    messagingSenderId: '455094239164',
    projectId: 'lebanon-driving-practice',
    storageBucket: 'lebanon-driving-practice.firebasestorage.app',
    iosBundleId: 'com.royapps.lebanondrivingexam.lebanonDrivingExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcUR4hgWcu_dly7ahpWUmIsJWG-xEiv8E',
    appId: '1:455094239164:web:f6633e4bdd36fe953ff5b9',
    messagingSenderId: '455094239164',
    projectId: 'lebanon-driving-practice',
    authDomain: 'lebanon-driving-practice.firebaseapp.com',
    storageBucket: 'lebanon-driving-practice.firebasestorage.app',
    measurementId: 'G-V53MG3VT47',
  );
}
